name: 'ai-job-tracker'
services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: jobtracker
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:12345678@db:5432/jobtracker
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - ./backend:/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
volumes:
  db_data:
